#!/bin/bash
# Usage
# ./make_and_go (directory) name
if [ "$#" -ne 1 ]; then
	printf "Usage: ./setup_python [dir_name]";
	exit 1;
fi
var1=$1
echo making $var1
mkdir $var1"_python"
cd $var1"_python"
touch input.txt
printf "import sys\n\nif __name__ == \"__main__\":\n    " >> "$var1".py
