default: Binary_Tree_Level_Order_Traversal.cpp
	g++ -ggdb -std=c++11 -Wpedantic -Wall -Wextra -Wzero-as-null-pointer-constant Binary_Tree_Level_Order_Traversal.cpp -o Binary_Tree_Level_Order_Traversal
